"""autogenerated by genpy from dcsl_messages/belugaInput.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class belugaInput(genpy.Message):
  _md5sum = "d7a8a4a3ad3fa031c886b7c16b438163"
  _type = "dcsl_messages/belugaInput"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#Actuator inputs for DCSL Beluga Robot
#Motor inputs are -255 to 255, positive values drive up and forwards respectively
int16 vertical_motor
int16 thrust_motor
#Servo inputs are -90 TO 90, postive values rotate motor X when viewed from above
int16 servo

"""
  __slots__ = ['vertical_motor','thrust_motor','servo']
  _slot_types = ['int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vertical_motor,thrust_motor,servo

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(belugaInput, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.vertical_motor is None:
        self.vertical_motor = 0
      if self.thrust_motor is None:
        self.thrust_motor = 0
      if self.servo is None:
        self.servo = 0
    else:
      self.vertical_motor = 0
      self.thrust_motor = 0
      self.servo = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3h.pack(_x.vertical_motor, _x.thrust_motor, _x.servo))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.vertical_motor, _x.thrust_motor, _x.servo,) = _struct_3h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3h.pack(_x.vertical_motor, _x.thrust_motor, _x.servo))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.vertical_motor, _x.thrust_motor, _x.servo,) = _struct_3h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3h = struct.Struct("<3h")
