# Determine whether to connect (the goal)
bool connect # True = connect miabot, False = Do nothing
int16 miabot_id # Number of the Miabot to connect to
---
# Determine if successfully connected (the result)
bool connected # True = Connected, False = Not connected
---
# Determine if robot is still connecting (feedback)
bool in_progress # True = still connecting, False = finished
